---
title: "CV & Publications"
output:
  distill::distill_article:
    toc: true
    toc_depth: 1
    toc_float: true
---

[**Full CV (PDF)**](https://jpheffne.github.io/joseph_heffner_cv_2024.pdf) \| [**Google Scholar**](https://scholar.google.com/citations?user=vtymOtoAAAAJ&hl=en)

# Publications

1. Gunsilius, C., **Heffner, J.**, Bruinsma, S., Corinha, M., Cortinez, M., Dalton, H., Duong, E., Lu, J., Omar, A., Long, L., Owen, W., Nazario Roarr, B., Tang, K., Petzschner, F. (2024). SOMAScience: A novel platform for multidimensional, longitudinal pain assessment, *JMIR mHealth and uHealth*. *shared first authorship*\
    [**Online**](https://mhealth.jmir.org/2024/1/e47177/) **\| [PDF](https://jpheffne.github.io/papers/SOMAScience_JMIR_2024.pdf)**

2. Vives, M., **Heffner, J.,** & FeldmanHall, O. (2023). Conceptual representations of uncertainty predict risky decision making. *Cognitive, Affective, and Behavioral Neuroscience.*\
    [**Online**](https://link.springer.com/article/10.3758/s13415-023-01090-8) **\| [PDF](https://jpheffne.github.io/papers/UncertaintyRep_CABN_2023.pdf) \| [Data & Code](https://github.com/jpheffne/uncertainty_rep)**
    
3. FeldmanHall, O., & **Heffner, J.** (2022). A generalizable framework for assessing the role of emotion during choice. *American Psychologist.*\
    [**Online**](https://psycnet.apa.org/record/2023-32731-010) **\| [PDF](https://jpheffne.github.io/papers/EmoFramework_AP_2022.pdf) **

4. **Heffner, J.**, & FeldmanHall, O. (2022). A probabilistic map of emotional experiences during competitive social interactions. *Nature Communications.*\
    [**Online**](https://www.nature.com/articles/s41467-022-29372-8) **\| [PDF](https://jpheffne.github.io/papers/EmotionMap_NC_2022.pdf) \| [Data & Code](https://github.com/jpheffne/NC_emotion_classify)**

2.  **Heffner, J.**, Son, J., & FeldmanHall, O. (2021). Emotion prediction errors guide socially adaptive behaviour. *Nature Human Behaviour.*\
    [**Online**](https://www.nature.com/articles/s41562-021-01213-6) **\| [PDF](https://jpheffne.github.io/papers/EPE_NHB_2021.pdf) \| [Data & Code](https://github.com/jpheffne/epe)**

3.  **Heffner, J.**, Vives, M., & FeldmanHall, O. (2021). Anxiety, gender, and social media consumption predict COVID-19 emotional distress. *Humanities and Social Science Communications*.\
    [**Online**](https://www.nature.com/articles/s41599-021-00816-8) **\| [PDF](https://jpheffne.github.io/papers/CovidModels_HSSC_2021.pdf) \| [Data & Code](https://github.com/jpheffne/covid_models)**

4.  **Heffner, J.**, Vives, M., & FeldmanHall, O. (2021). Emotional responses to prosocial messages increase willingness to self-isolate during the COVID-19 pandemic. *Personality and Individual Differences*.\
    [**Online**](https://www.sciencedirect.com/science/article/pii/S0191886920306115) **\| [PDF](https://jpheffne.github.io/papers/CovidEmotions_PIN_2021.pdf) \| [Data & Code](https://github.com/jpheffne/covid_intervention)**
    
5.  **Heffner, J.**, & FeldmanHall, O. (2019). Why we don't always punish: Preference for non-punitive responses to moral violations. *Scientific Reports*.\
    [**Online**](https://www.nature.com/articles/s41598-019-49680-2) **\| [PDF](https://jpheffne.github.io/papers/PunishAlts_SciRep_2019.pdf) \| [Data & Code](https://osf.io/ft9bv/)**

6.  FeldmanHall, O., Son, J., & **Heffner, J.** (2018). Norms and the flexibility of moral action. *Personality Neuroscience.*\
    [**Online**](https://www.cambridge.org/core/journals/personality-neuroscience/article/norms-and-the-flexibility-of-moral-action/A8A5140A517ECEE314A21FF9FE0E9EED) **\| [PDF](https://jpheffne.github.io/papers/NormsMoralAction_PN_2018.pdf)**
    
7.  Schaich Borg, J., Srivastava, S., Lin, L., **Heffner, J.**, Dunson, D., Dzirasa, K., & Lecesa, L. (2017). Rat intersubjective decisions are encoded by frequency-specific oscillatory contexts. *Brain and Behavior.*\
    [**Online**](https://onlinelibrary.wiley.com/doi/10.1002/brb3.710) **\| [PDF](https://jpheffne.github.io/papers/RatEmpathy_BB_2017.pdf)**
    
8.  Strohminger, N., Gray, K., Chituc, V., **Heffner, J.**, & Heagins, T. B. (2016). The MR2: A multi-racial, mega-resolution database of facial stimuli. *Behavior Research Methods.*\
    [**Online**](https://link.springer.com/article/10.3758/s13428-015-0641-9) **\| [PDF](https://jpheffne.github.io/papers/MR2_BRM_2016.pdf)**

```{r echo=FALSE}
htmltools::p(
  "
  Disclaimer: The provided PDFs may be copyrighted by the journals
  in which they are published. Access to these articles is provided to facilitate
  timely distribution of scientific knowledge, and is therefore intended for your
  personal use only. No commercial use may be made of these articles, nor is mass
  production of these articles permitted.
  ",
  style = "font-size: 70%; font-style: italic"
)
```

# Experience

-   **Post-Doctoral Associate** (2022 - Present)

    -   Yale University, Department of Psychology
    -   Supervisor: Robb Rutledge

-   **Ph.D.** (2016 - 2022)

    -   Brown University, Dept. of Cognitive, Linguistic, & Psychological Sciences (CLPS)
    -   Supervisor: Oriel FeldmanHall

-   **Project Manager** (2013 - 2016)

    -   Duke University, Kenan Institute for Ethics
    -   Supervisor: Walter Sinnott-Armstrong

-   **B.S. & B.A.** (2009 - 2013)

    -   University of Chapel Hill at North Carolina
    -   Supervisor: Keith Payne